'use client';

import { useCallback } from 'react';
import { saveAs } from 'file-saver';

interface UseTreeImageExportOptions {
  treeString: string;
  repoName: string | null;
}

export function useTreeImageExport({ treeString, repoName }: UseTreeImageExportOptions) {
  const sanitizeRepoName = (name: string | null): string => {
    if (!name) return 'repository';
    return name.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
  };

  const exportAsSvg = useCallback(() => {
    const repoNameSanitized = sanitizeRepoName(repoName);
    const filename = `${repoNameSanitized}-tree.svg`;

    const container = document.createElement('div');
    container.style.cssText = 'position: absolute; left: -9999px; top: -9999px;';
    document.body.appendChild(container);

    const svgElement = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
    container.appendChild(svgElement);

    const lines = treeString.split('\n');
    const fontSize = 13;
    const charWidth = fontSize * 0.6;
    const lineHeight = fontSize * 1.6;
    const padding = { top: 24, right: 32, bottom: 24, left: 32 };
    const headerHeight = 48;
    const watermarkHeight = 32;
    const titleBarPadding = 20;

    const maxLen = Math.max(...lines.map(l => l.length), 0);
    const contentWidth = maxLen * charWidth;
    const contentHeight = lines.length * lineHeight;
    const cardWidth = Math.max(600, contentWidth + padding.left + padding.right + titleBarPadding * 2);
    const cardHeight = headerHeight + contentHeight + padding.top + padding.bottom + watermarkHeight;

    svgElement.setAttribute('xmlns', 'http://www.w3.org/2000/svg');
    svgElement.setAttribute('width', String(Math.ceil(cardWidth)));
    svgElement.setAttribute('height', String(Math.ceil(cardHeight)));
    svgElement.setAttribute('viewBox', `0 0 ${Math.ceil(cardWidth)} ${Math.ceil(cardHeight)}`);
    svgElement.style.fontFamily = 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace';

    const escapeXml = (str: string): string => {
      return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
    };

    svgElement.innerHTML = `
      <defs>
        <linearGradient id="treeExportGradient" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stop-color="#667eea"/>
          <stop offset="50%" stop-color="#764ba2"/>
          <stop offset="100%" stop-color="#f093fb"/>
        </linearGradient>
        <filter id="treeExportShadow" x="-20%" y="-20%" width="140%" height="140%">
          <feDropShadow dx="0" dy="8" stdDeviation="16" flood-color="#000000" flood-opacity="0.25"/>
        </filter>
      </defs>
      <rect x="0" y="0" width="${Math.ceil(cardWidth)}" height="${Math.ceil(cardHeight)}" fill="url(#treeExportGradient)"/>
      <rect x="20" y="20" width="${Math.ceil(cardWidth) - 40}" height="${Math.ceil(cardHeight) - 40}" rx="16" ry="16" fill="#0d1117" filter="url(#treeExportShadow)"/>
      <rect x="20" y="20" width="${Math.ceil(cardWidth) - 40}" height="48" rx="16" ry="16" fill="#161b22"/>
      <rect x="20" y="52" width="${Math.ceil(cardWidth) - 40}" height="16" fill="#161b22"/>
      <circle cx="16" cy="${padding.top}" r="6" fill="#ff5f57"/>
      <circle cx="36" cy="${padding.top}" r="6" fill="#febc2e"/>
      <circle cx="56" cy="${padding.top}" r="6" fill="#28c840"/>
      <text x="${Math.ceil(cardWidth / 2)}" y="${padding.top + 1}" text-anchor="middle" dominant-baseline="middle" fill="#e6edf3" font-size="${fontSize}" font-weight="600">${escapeXml(repoName || 'Repository')}</text>
      ${lines.map((line, i) => `<text x="${padding.left + titleBarPadding}" y="${padding.top + headerHeight + (lineHeight * 0.75) + (i * lineHeight)}" fill="#8b949e" font-size="${fontSize}">${escapeXml(line)}</text>`).join('')}
      <text x="${Math.ceil(cardWidth / 2)}" y="${Math.ceil(cardHeight) - 16}" text-anchor="middle" dominant-baseline="middle" fill="#484f58" font-size="11">Generated by RepoTree</text>
    `;

    const svgData = new XMLSerializer().serializeToString(svgElement);
    const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
    saveAs(svgBlob, filename);

    document.body.removeChild(container);
  }, [treeString, repoName]);

  const exportAsPng = useCallback(async () => {
    const repoNameSanitized = sanitizeRepoName(repoName);
    const filename = `${repoNameSanitized}-tree.png`;

    const container = document.createElement('div');
    container.style.cssText = 'position: absolute; left: -9999px; top: -9999px; display: inline-block;';
    document.body.appendChild(container);

    const wrapper = document.createElement('div');
    container.appendChild(wrapper);

    wrapper.innerHTML = (() => {
      const lines = treeString.split('\n');
      const fontSize = 13;
      const charWidth = fontSize * 0.6;
      const lineHeight = fontSize * 1.6;
      const padding = { top: 24, right: 32, bottom: 24, left: 32 };
      const headerHeight = 48;
      const watermarkHeight = 32;
      const titleBarPadding = 20;

      const maxLen = Math.max(...lines.map(l => l.length), 0);
      const contentWidth = maxLen * charWidth;
      const contentHeight = lines.length * lineHeight;
      const cardWidth = Math.max(600, contentWidth + padding.left + padding.right + titleBarPadding * 2);
      const cardHeight = headerHeight + contentHeight + padding.top + padding.bottom + watermarkHeight;

      const escapeXml = (str: string): string => {
        return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
      };

      return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${Math.ceil(cardWidth)}" height="${Math.ceil(cardHeight)}" viewBox="0 0 ${Math.ceil(cardWidth)} ${Math.ceil(cardHeight)}" style="font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace">
  <defs>
    <linearGradient id="treeExportGradient" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#667eea"/>
      <stop offset="50%" stop-color="#764ba2"/>
      <stop offset="100%" stop-color="#f093fb"/>
    </linearGradient>
    <filter id="treeExportShadow" x="-20%" y="-20%" width="140%" height="140%">
      <feDropShadow dx="0" dy="8" stdDeviation="16" flood-color="#000000" flood-opacity="0.25"/>
    </filter>
  </defs>
  <rect x="0" y="0" width="${Math.ceil(cardWidth)}" height="${Math.ceil(cardHeight)}" fill="url(#treeExportGradient)"/>
  <rect x="20" y="20" width="${Math.ceil(cardWidth) - 40}" height="${Math.ceil(cardHeight) - 40}" rx="16" ry="16" fill="#0d1117" filter="url(#treeExportShadow)"/>
  <rect x="20" y="20" width="${Math.ceil(cardWidth) - 40}" height="48" rx="16" ry="16" fill="#161b22"/>
  <rect x="20" y="52" width="${Math.ceil(cardWidth) - 40}" height="16" fill="#161b22"/>
  <circle cx="16" cy="${padding.top}" r="6" fill="#ff5f57"/>
  <circle cx="36" cy="${padding.top}" r="6" fill="#febc2e"/>
  <circle cx="56" cy="${padding.top}" r="6" fill="#28c840"/>
  <text x="${Math.ceil(cardWidth / 2)}" y="${padding.top + 1}" text-anchor="middle" dominant-baseline="middle" fill="#e6edf3" font-size="${fontSize}" font-weight="600">${escapeXml(repoName || 'Repository')}</text>
  ${lines.map((line, i) => `<text x="${padding.left + titleBarPadding}" y="${padding.top + headerHeight + (lineHeight * 0.75) + (i * lineHeight)}" fill="#8b949e" font-size="${fontSize}">${escapeXml(line)}</text>`).join('')}
  <text x="${Math.ceil(cardWidth / 2)}" y="${Math.ceil(cardHeight) - 16}" text-anchor="middle" dominant-baseline="middle" fill="#484f58" font-size="11">Generated by RepoTree</text>
</svg>`;
    })();

    const svgElement = wrapper.querySelector('svg');
    if (!svgElement) {
      document.body.removeChild(container);
      return;
    }

    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) {
      document.body.removeChild(container);
      return;
    }

    const img = new Image();
    const svgData = new XMLSerializer().serializeToString(svgElement);
    const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(svgBlob);

    try {
      await new Promise<void>((resolve, reject) => {
        img.onload = () => {
          const scale = 2;
          canvas.width = svgElement.clientWidth * scale;
          canvas.height = svgElement.clientHeight * scale;
          ctx.scale(scale, scale);
          ctx.drawImage(img, 0, 0);
          URL.revokeObjectURL(url);
          resolve();
        };
        img.onerror = () => {
          URL.revokeObjectURL(url);
          reject(new Error('Failed to load SVG'));
        };
        img.src = url;
      });

      canvas.toBlob((blob) => {
        if (blob) {
          saveAs(blob, filename);
        }
      }, 'image/png');
    } catch (error) {
      console.error('Error exporting PNG:', error);
    } finally {
      document.body.removeChild(container);
    }
  }, [treeString, repoName]);

  return {
    exportAsSvg,
    exportAsPng,
  };
}

export default useTreeImageExport;
